### ISSUE TITLE
Provide alternatives for CI-1: Avoid Context Properties

### ISSUE THREAD

**Issue by Daguerreo** [Furkanzmc/QML-Coding-Guide#10]
CI-1: Avoid Context Properties

Should be useful provide alternative to using context properties, like referring to singleton or qml registered type.

**Comment by OlivierLDff** [comment]
Lots have been discussed here : https://github.com/Furkanzmc/QML-Coding-Guide/issues/9

**Comment by Furkanzmc** [comment]
I also incorporated our discussions into the guideline with this commit: https://github.com/Furkanzmc/QML-Coding-Guide/commit/559f8b75e5f0193346187024ce09d18c74f04e8a

I believe the following items already provide an alternative. Although, it may not have come across that way. I'll see If I can improve it.

Thanks for raising the issue @Daguerreo .

And thanks for referring to the discussion @OlivierLDff.
