### ISSUE TITLE
Not 100% compliant with qml coding conventions

### ISSUE THREAD

**Issue by rferrazz** [Furkanzmc/QML-Coding-Guide#2]
https://doc.qt.io/qt-5/qml-codingconventions.html

**Comment by Furkanzmc** [comment]
I think coding conventions are subjective and personal taste plays a big role. I chose the style laid out in the documentation based on my personal taste. It seems that a lot of people already adopted that version.

The most common suggestion was to put the `id` property at the top and I did mention that could be done alternatively in the documentation but I guess I need to make it more clear.

If you have specific points you think should be adopted here as well, please mention those and I'd be happy to make the changes.

**Comment by rferrazz** [comment]
To be honest the only thing popping into my eyes was the id not on top.

**Comment by Furkanzmc** [comment]
If that's the case, I will edit the file and put all the `id` deceleration at the top. I'll make that change later today.

Thanks Riccardo.

**Comment by rferrazz** [comment]
Thank you for this documentation. It is a precious resource. It would be nice to have an automated way of enforcing a well defined coding style for QML
