### ISSUE TITLE
Linter / formatter rules

### ISSUE THREAD

**Issue by ratijas** [Furkanzmc/QML-Coding-Guide#5]
Nice guide!

Any chances to make it into a linter / formatter rules, maybe for qmllint?

Enforcing some of options, especially imports ordering, would be extremely good to have ON by default.

**Comment by Furkanzmc** [comment]
`qmllint` doesn't support any of the rules from this guideline yet. I'm hoping that at some point in the future, they will be integrated into the linter but for that to happen these rules need to mature and be validated by others so there's merit to adding them to the linter.

I'm hoping that other QML developers will also join in, and pitch their ideas so we can discuss and come to a consensus together. At that point, I'm planning to submit patches to `qmllint` for these.

**Comment by ratijas** [comment]
Maybe an independent QML tooling should be developed, I think. That way it could evolve more quickly, and allow more freedom for experiments. Then, if proven handy, it might as well get cherry-picked into qmllist.

**Comment by Furkanzmc** [comment]
That's a good point. I'll fork the existing `qmllint` and start incorporating some of the guidelines from here. Thanks ratijas.
